version: '3'
services:
  web:
    image: web_c
    build: web
    container_name: web_c
    ports:
    - "580:80"
    volumes:
      - ./html:/var/www/html
  db:
    image: mariadb
    container_name: mysql_c
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: "mysql_pass"
  adminer:
    image: adminer:latest
    container_name: adminer_c
    restart: always
    ports:
      - 680:8080
  php:
    image: php:7.4-fpm-alpine3.13
    container_name: php_c
    volumes:
      - ./html:/var/www/html


  # comment

  



